// <auto-generated />
using System;
using EmpresaX.POS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmpresaX.POS.API.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    partial class FinanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("EmpresaX.POS.API.Models.Finance.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativa = true,
                            DataCriacao = new DateTime(2025, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Receitas de vendas",
                            Nome = "Vendas",
                            Tipo = "Receita"
                        },
                        new
                        {
                            Id = 2,
                            Ativa = true,
                            DataCriacao = new DateTime(2025, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Receitas de serviços",
                            Nome = "Serviços",
                            Tipo = "Receita"
                        },
                        new
                        {
                            Id = 3,
                            Ativa = true,
                            DataCriacao = new DateTime(2025, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Pagamentos a fornecedores",
                            Nome = "Fornecedores",
                            Tipo = "Despesa"
                        },
                        new
                        {
                            Id = 4,
                            Ativa = true,
                            DataCriacao = new DateTime(2025, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Folha de pagamento",
                            Nome = "Salários",
                            Tipo = "Despesa"
                        },
                        new
                        {
                            Id = 5,
                            Ativa = true,
                            DataCriacao = new DateTime(2025, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Despesas com aluguel",
                            Nome = "Aluguel",
                            Tipo = "Despesa"
                        });
                });

            modelBuilder.Entity("EmpresaX.POS.API.Models.Finance.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Agencia")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Banco")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroConta")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativa = true,
                            DataCriacao = new DateTime(2025, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Caixa Principal",
                            SaldoInicial = 5000m,
                            Tipo = "Caixa"
                        },
                        new
                        {
                            Id = 2,
                            Agencia = "1234",
                            Ativa = true,
                            Banco = "Santander",
                            DataCriacao = new DateTime(2025, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Banco Santander",
                            NumeroConta = "123456-7",
                            SaldoInicial = 15000m,
                            Tipo = "Banco"
                        },
                        new
                        {
                            Id = 3,
                            Agencia = "5678",
                            Ativa = true,
                            Banco = "Itaú",
                            DataCriacao = new DateTime(2025, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Banco Itaú",
                            NumeroConta = "987654-3",
                            SaldoInicial = 8000m,
                            Tipo = "Banco"
                        });
                });

            modelBuilder.Entity("EmpresaX.POS.API.Models.Finance.FechamentoCaixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFechamento")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Diferenca")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoFinal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SaldoInformado")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalEntradas")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalSaidas")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ContaId");

                    b.ToTable("FechamentosCaixa");
                });

            modelBuilder.Entity("EmpresaX.POS.API.Models.Finance.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Conciliado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaId");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("EmpresaX.POS.API.Models.Finance.FechamentoCaixa", b =>
                {
                    b.HasOne("EmpresaX.POS.API.Models.Finance.Conta", "Conta")
                        .WithMany("Fechamentos")
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("EmpresaX.POS.API.Models.Finance.Movimentacao", b =>
                {
                    b.HasOne("EmpresaX.POS.API.Models.Finance.Categoria", "Categoria")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmpresaX.POS.API.Models.Finance.Conta", "Conta")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("EmpresaX.POS.API.Models.Finance.Categoria", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("EmpresaX.POS.API.Models.Finance.Conta", b =>
                {
                    b.Navigation("Fechamentos");

                    b.Navigation("Movimentacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
